"""
Project 16: Long-Context Extension (RoPE, YaRN, NTK-Aware)

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Extend the context window with no fix and watch it break ===

# Naive extension: just feed longer inputs to a model
# whose RoPE was trained at max_seq_len = 1024.
context_lengths = [1024, 1536, 2048, 4096]
baseline_ppl = {}
for L in context_lengths:
    ppl = evaluate_perplexity(model, eval_dataset, seq_len=L)
    baseline_ppl[L] = ppl
    print(f"length={L}, ppl={ppl:.2f}")

# === Step 2: Implement position interpolation ===

class RopePI:
    def __init__(self, head_dim, base=10000.0,
                 train_seq_len=1024, target_seq_len=4096):
        self.head_dim = head_dim
        self.base = base
        self.k = target_seq_len / train_seq_len
        inv_freq = 1.0 / (base ** (torch.arange(0, head_dim, 2).float()
                                   / head_dim))
        self.inv_freq = inv_freq  # frequencies unchanged

    def angles(self, positions):
        # positions: (seq_len,)
        scaled = positions.float() / self.k
        # outer product: (seq_len, head_dim/2)
        return scaled[:, None] * self.inv_freq[None, :]

# === Step 3: Re-measure perplexity with PI ===

model.set_rope(RopePI(head_dim=64, base=10000.0,
                     train_seq_len=1024, target_seq_len=4096))
pi_ppl = {}
for L in context_lengths:
    pi_ppl[L] = evaluate_perplexity(model, eval_dataset, seq_len=L)
    print(f"PI: length={L}, ppl={pi_ppl[L]:.2f}")

# === Step 4: Implement NTK-aware scaling ===

class RopeNTK:
    def __init__(self, head_dim, base=10000.0,
                 train_seq_len=1024, target_seq_len=4096):
        self.head_dim = head_dim
        k = target_seq_len / train_seq_len
        # NTK-aware base adjustment: stretches the slow pairs,
        # leaves the fast pairs nearly untouched.
        new_base = base * (k ** (head_dim / (head_dim - 2)))
        inv_freq = 1.0 / (new_base ** (torch.arange(0, head_dim, 2).float()
                                       / head_dim))
        self.inv_freq = inv_freq  # frequencies modified

    def angles(self, positions):
        return positions.float()[:, None] * self.inv_freq[None, :]

# === Step 5: Re-measure perplexity and compare PI vs NTK ===

model.set_rope(RopeNTK(head_dim=64, base=10000.0,
                      train_seq_len=1024, target_seq_len=4096))
ntk_ppl = {}
for L in context_lengths:
    ntk_ppl[L] = evaluate_perplexity(model, eval_dataset, seq_len=L)
    print(f"NTK: length={L}, ppl={ntk_ppl[L]:.2f}")

# === Step 6: Implement YaRN ===

class RopeYaRN:
    def __init__(self, head_dim, base=10000.0,
                 train_seq_len=1024, target_seq_len=4096,
                 alpha=1, beta=32):
        self.head_dim = head_dim
        self.k = target_seq_len / train_seq_len

        # Identify per-pair regime: which pairs have rotated
        # enough times in training to be safe from extension?
        dims = torch.arange(0, head_dim, 2).float()
        freqs = 1.0 / (base ** (dims / head_dim))
        rotations_in_train = freqs * train_seq_len / (2 * math.pi)

        # NTK-by-parts mask: smooth ramp between alpha and beta
        # rotations. Below alpha: full PI. Above beta: no change.
        mask = torch.clamp((rotations_in_train - alpha)
                           / (beta - alpha), 0.0, 1.0)
        self.inv_freq = freqs * (mask + (1 - mask) / self.k)

        # YaRN attention temperature
        self.attn_temperature = 0.1 * math.log(self.k) + 1.0

    def angles(self, positions):
        return positions.float()[:, None] * self.inv_freq[None, :]

    def scale_attention(self, attn_logits):
        return attn_logits / self.attn_temperature

model.set_rope(RopeYaRN(head_dim=64, base=10000.0,
                       train_seq_len=1024, target_seq_len=4096))
yarn_ppl = {}
for L in context_lengths:
    yarn_ppl[L] = evaluate_perplexity(model, eval_dataset, seq_len=L)
    print(f"YaRN: length={L}, ppl={yarn_ppl[L]:.2f}")

# === Step 7: Fine-tune briefly on long context ===

# Apply YaRN rotation
model.set_rope(RopeYaRN(...))

# Long-context fine-tune
long_dataset = LongContextDataset(tokenizer,
                                  files=long_docs,
                                  seq_len=4096)
optimizer = torch.optim.AdamW(model.parameters(),
                              lr=2e-5)

for step in range(1000):
    batch = next(long_dataset)
    loss = model(batch).loss
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
    optimizer.step()
    optimizer.zero_grad()
    if step % 50 == 0:
        print(f"step {step}, loss {loss.item():.3f}")

# === Step 8: Needle-in-a-haystack recall ===

def make_haystack(filler, needle, position_frac, total_len):
    # Build a context of length total_len with the needle
    # inserted at position_frac through the document.
    needle_pos = int(total_len * position_frac)
    tokens = tokenize(filler)[:total_len]
    needle_tokens = tokenize(needle)
    tokens[needle_pos:needle_pos+len(needle_tokens)] = needle_tokens
    return tokens

def needle_test(model, position_fracs, total_lens):
    results = {}
    for L in total_lens:
        for frac in position_fracs:
            ctx = make_haystack(filler, "The secret number is 1729.",
                                frac, L)
            prompt = ctx + tokenize(" What is the secret number?")
            answer = model.generate(prompt, max_new_tokens=10)
            results[(L, frac)] = "1729" in answer
    return results
