"""
Project 18: Mixture Of Experts

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Isolate the FFN boundary ===

x = x + self.attn(self.norm1(x))
x = x + self.ffn(self.norm2(x))

# === Step 2: Build one expert ===

class Expert(nn.Module):
    def __init__(self, d_model: int, d_ff: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.GELU(),
            nn.Linear(d_ff, d_model),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)

# === Step 3: Add multiple experts ===

self.experts = nn.ModuleList([
    Expert(d_model, d_ff) for _ in range(num_experts)
])

# === Step 4: Add the router ===

self.router = nn.Linear(d_model, num_experts, bias=False)

# === Step 5: Convert scores into routing probabilities ===

router_logits = self.router(x)           # (B, T, N)
router_probs = torch.softmax(router_logits, dim=-1)

# === Step 6: Select the top-k experts ===

topk_probs, topk_idx = torch.topk(router_probs, k=2, dim=-1)

topk_probs = topk_probs / topk_probs.sum(dim=-1, keepdim=True)

# === Step 7: Run only the chosen experts ===

expert_outputs = torch.stack([expert(x) for expert in self.experts], dim=2)
# shape: (B, T, N, d)

mask = torch.zeros_like(router_probs)
mask.scatter_(-1, topk_idx, topk_probs)
# shape: (B, T, N)

y = (expert_outputs * mask.unsqueeze(-1)).sum(dim=2)
# shape: (B, T, d)

# === Step 8: Replace one block's FFN with the MoE layer ===

x = x + self.attn(self.norm1(x))
x = x + self.moe(self.norm2(x))

# === Step 9: Track expert utilization ===

with torch.no_grad():
    flat_idx = topk_idx.reshape(-1)
    counts = torch.bincount(flat_idx, minlength=num_experts)

# === Step 11: Add the load-balancing auxiliary loss ===

importance = router_probs.mean(dim=(0, 1))  # (N,)
load = mask.sum(dim=(0, 1)) / mask.sum()    # (N,)

aux_loss = num_experts * torch.sum(importance * load)

loss = lm_loss + alpha * aux_loss
