"""
Project 33: The Interface Specification

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 5: Make specialists declare what they are ===

ckpt["interface"] = {
    "interface_name": "COMPOSE-LLM-IFACE",
    "interface_version": "1.0",
    "base_model_id": "trunk-init-2026-03",
    "shared_prefix_depth": 8,
    "d_model": 768,
    "n_heads": 12,
    "norm_type": "RMSNorm",
    "norm_eps": 1e-5,
    "positional_encoding": "RoPE",
    "rope_theta": 10000,
    "tokenizer_hash": "sha256:..."
}

# === Step 6: Inspect the actual module, not just the metadata ===

import torch

def check_norm_type(module: torch.nn.Module, expected: str) -> None:
    actual = type(module.norm).__name__
    if actual != expected:
        raise ValueError(f"Norm mismatch: expected {expected}, found {actual}")

def check_d_model(module: torch.nn.Module, expected: int) -> None:
    actual = module.attn.q_proj.weight.shape[1]
    if actual != expected:
        raise ValueError(f"d_model mismatch: expected {expected}, found {actual}")

def check_vocab_size(module: torch.nn.Module, expected: int) -> None:
    actual = module.lm_head.weight.shape[0]
    if actual != expected:
        raise ValueError(f"Vocab mismatch: expected {expected}, found {actual}")

# === Step 7: Check behavior, not just structure ===

with torch.no_grad():
    x = reference_hidden_state  # fixed saved tensor [B, T, 768]
    y = specialist(x)

    if torch.isnan(y).any():
        raise ValueError("Dynamic check failed: NaNs in output")

    rms = y.pow(2).mean().sqrt().item()
    if not (0.1 < rms < 10.0):
        raise ValueError(f"Dynamic check failed: output RMS out of range: {rms:.4f}")

# === Step 10: Build the compliance script ===

def run_compliance(spec: dict, ckpt_path: str) -> tuple[list, list]:
    model, metadata = load_specialist(ckpt_path)
    failures = []
    warnings = []

    # Declaration checks
    if metadata["interface_name"] != spec["interface_name"]:
        failures.append((
            "interface_name",
            spec["interface_name"],
            metadata["interface_name"],
        ))

    # Structural checks
    actual_norm = detect_boundary_norm(model)
    expected_norm = spec["normalization"]["type"]
    if actual_norm != expected_norm:
        failures.append(("normalization.type", expected_norm, actual_norm))

    actual_d_model = detect_d_model(model)
    if actual_d_model != spec["boundary"]["d_model"]:
        failures.append((
            "boundary.d_model",
            spec["boundary"]["d_model"],
            actual_d_model,
        ))

    # Dynamic checks
    dyn_msg = run_probe(model, spec)
    if dyn_msg is not None:
        failures.append(("dynamic_probe", "pass", dyn_msg))

    return failures, warnings
