"""
Project 13: Fast Inference: The KV Cache

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Start with naive autoregressive generation ===

@torch.no_grad()
def generate_naive(model: nn.Module, idx: torch.Tensor, max_new_tokens: int, temperature: float = 1.0) -> torch.Tensor:
    # idx: [B, T]
    for _ in range(max_new_tokens):
        logits = model(idx)              # full forward pass on full sequence
        last = logits[:, -1, :] / temperature
        next_id = torch.argmax(last, dim=-1, keepdim=True)
        idx = torch.cat([idx, next_id], dim=1)
    return idx

import time

import torch

def bench(fn, *args, new_tokens: int = 128, warmup: int = 1, runs: int = 3, **kwargs) -> float:
    for _ in range(warmup):
        _ = fn(*args, max_new_tokens=new_tokens, **kwargs)
    torch.cuda.synchronize() if torch.cuda.is_available() else None

    start = time.perf_counter()
    for _ in range(runs):
        _ = fn(*args, max_new_tokens=new_tokens, **kwargs)
    torch.cuda.synchronize() if torch.cuda.is_available() else None
    dt = time.perf_counter() - start
    return (runs * new_tokens) / dt

# === Step 2: Identify where K and V are created ===

q = q_proj(x)
k = k_proj(x)
v = v_proj(x)

# === Step 3: Add a cache object per layer ===

class KVCache:
    def __init__(self, n_layers):
        self.k = [None] * n_layers
        self.v = [None] * n_layers

k_cache[layer]  # [B, H, T_max, d_head]
v_cache[layer]  # [B, H, T_max, d_head]

k_cache[layer][:, :, pos:pos+1, :] = k_new
v_cache[layer][:, :, pos:pos+1, :] = v_new

# === Step 4: Change attention to decode one token at a time ===

def decode_step(x_new: torch.Tensor, k_cache: torch.Tensor, v_cache: torch.Tensor, pos: int) -> torch.Tensor:
    q_new = q_proj(x_new)
    k_new = k_proj(x_new)
    v_new = v_proj(x_new)

    q_new = split_heads(q_new)  # [B, H, 1, d]
    k_new = split_heads(k_new)  # [B, H, 1, d]
    v_new = split_heads(v_new)  # [B, H, 1, d]

    k_cache[:, :, pos:pos+1, :] = k_new
    v_cache[:, :, pos:pos+1, :] = v_new

    k_all = k_cache[:, :, :pos+1, :]
    v_all = v_cache[:, :, :pos+1, :]

    scores = q_new @ k_all.transpose(-2, -1) / math.sqrt(q_new.size(-1))
    att = scores.softmax(dim=-1)
    out = att @ v_all
    return merge_heads(out)

# === Step 5: Thread the cache through the full model ===

logits, cache = model.prefill(prompt_ids, cache=None)
next_logits, cache = model.decode(next_token, cache)

logits = model(idx, cache=cache, use_cache=True)

# === Step 8: Add a sliding window ===

if cache_len > window:
    k_cache = k_cache[:, :, -window:, :]
    v_cache = v_cache[:, :, -window:, :]
