"""
Project 12: Distributed Training: FSDP and ZeRO (Single-Box Proxy)

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Launch two PyTorch processes on one box ===

import os
import torch
import torch.distributed as dist
import torch.multiprocessing as mp

def worker(rank: int, world_size: int):
    os.environ["MASTER_ADDR"] = "127.0.0.1"
    os.environ["MASTER_PORT"] = "29500"
    dist.init_process_group(
        backend="gloo",
        rank=rank,
        world_size=world_size,
    )
    x = torch.tensor([float(rank + 1)])
    dist.all_reduce(x, op=dist.ReduceOp.SUM)
    print(f"rank {rank} saw {x.item()}")
    dist.destroy_process_group()

if __name__ == "__main__":
    mp.spawn(worker, args=(2,), nprocs=2, join=True)

# === Step 2: Implement parameter sharding by hand ===

class HandShardedLinear:
    def __init__(self, in_dim: int, out_dim: int, rank: int, world_size: int):
        self.in_dim = in_dim
        self.out_dim = out_dim
        self.rank = rank
        self.world_size = world_size
        total = in_dim * out_dim
        assert total % world_size == 0, "shard must divide evenly"
        shard_size = total // world_size
        self.shard_start = rank * shard_size
        self.shard_end = (rank + 1) * shard_size
        # Each rank initializes only its own slice.
        torch.manual_seed(0)  # deterministic across ranks
        full_init = torch.randn(total) * 0.02
        self.flat_shard = full_init[self.shard_start:self.shard_end].clone()
        self.flat_shard.requires_grad_(True)

def gather_full_weight(self) -> torch.Tensor:
    pieces = [torch.empty_like(self.flat_shard) for _ in range(self.world_size)]
    dist.all_gather(pieces, self.flat_shard)
    full_flat = torch.cat(pieces, dim=0)
    return full_flat.view(self.out_dim, self.in_dim)

def forward(self, x: torch.Tensor) -> torch.Tensor:
    W = self.gather_full_weight()
    y = x @ W.t()
    # Important: in real FSDP the full W is freed immediately after use,
    # so it does not stay in memory beyond this scope.
    return y

# === Step 3: All-gather and reduce-scatter, drawn out ===

def backward_step(self, grad_full_weight: torch.Tensor):
    # grad_full_weight has shape (out_dim, in_dim), same as the full weight.
    grad_flat = grad_full_weight.reshape(-1)
    # Each rank starts with the full gradient (computed locally on its batch).
    # We need reduce-scatter to sum across ranks and keep only this rank's slice.
    out = torch.empty_like(self.flat_shard)
    dist.reduce_scatter_tensor(out, grad_flat, op=dist.ReduceOp.SUM)
    # Now `out` is the summed gradient for this rank's shard.
    self.flat_shard.grad = out

# === Step 5: Wrap the Project 9 GPT in real FSDP ===

import torch
import torch.distributed as dist
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP
from torch.distributed.fsdp.wrap import transformer_auto_wrap_policy
from functools import partial
from nanochat.model import GPT, TransformerBlock  # from Project 9

def setup_fsdp_model(config):
    model = GPT(config)
    wrap_policy = partial(
        transformer_auto_wrap_policy,
        transformer_layer_cls={TransformerBlock},
    )
    sharded = FSDP(
        model,
        auto_wrap_policy=wrap_policy,
        device_id=torch.cuda.current_device() if torch.cuda.is_available() else None,
    )
    return sharded

model = setup_fsdp_model(config)
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4)

for step, batch in enumerate(loader):
    inputs, targets = batch
    logits = model(inputs)
    loss = compute_loss(logits, targets)
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
    optimizer.step()
    optimizer.zero_grad()
