"""
Project 9: Pretraining On The Real Web

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 2: Annotate `prepare.py` like a systems engineer ===

# Input: dataset rows with raw text and metadata
# Operation: keep only the text field
# Output: plain text documents
# Why here: avoids carrying useless metadata into tokenization and storage

# Input: one text document
# Operation: tokenize into integer IDs and append end-of-document token
# Output: list of token IDs for one document
# Why here: preserves document boundaries and makes training data
#   ready for direct loading

# Input: many tokenized documents
# Operation: pack tokens into shard-sized arrays and write to disk
# Output: shard files containing integer token IDs
# Why here: training can stream tokens directly without repeated preprocessing
