"""
Project 5: Your GPT From A Blank File

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Decide the smallest complete system ===

from dataclasses import dataclass

@dataclass
class Config:
    batch_size = 64
    block_size = 128
    d_model = 256
    n_heads = 4
    n_layers = 6
    dropout = 0.2
    learning_rate = 3e-4
    min_lr = 3e-5
    warmup_steps = 200
    max_steps = 10000
    eval_interval = 200
    eval_steps = 50
    grad_clip = 1.0
    device = "cuda"

# === Step 2: Load text and tokenize it ===

chars = sorted(list(set(text)))
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for ch, i in stoi.items()}

def encode(s):
    return [stoi[c] for c in s]

def decode(ids):
    return "".join(itos[i] for i in ids)

n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

# === Step 3: Write the batch sampler honestly ===

def get_batch(split: str, cfg: 'Config') -> tuple:
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - cfg.block_size - 1, (cfg.batch_size,))
    x = torch.stack([data[i:i+cfg.block_size] for i in ix])
    y = torch.stack([data[i+1:i+cfg.block_size+1] for i in ix])
    return x.to(cfg.device), y.to(cfg.device)

# === Step 4: Build the transformer pieces ===

tok = self.token_embedding(idx)          # (B, T, d_model)
pos = self.position_embedding(pos_ids)   # (T, d_model)
x = tok + pos

class CausalSelfAttention(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        assert cfg.d_model % cfg.n_heads == 0
        self.n_heads = cfg.n_heads
        self.head_dim = cfg.d_model // cfg.n_heads
        self.qkv = nn.Linear(cfg.d_model, 3 * cfg.d_model)
        self.proj = nn.Linear(cfg.d_model, cfg.d_model)
        self.dropout = nn.Dropout(cfg.dropout)
        self.register_buffer(
            "mask",
            torch.tril(torch.ones(cfg.block_size, cfg.block_size))
                .view(1, 1, cfg.block_size, cfg.block_size)
        )

    def forward(self, x):
        B, T, C = x.shape
        qkv = self.qkv(x)
        q, k, v = qkv.split(C, dim=2)

        q = q.view(B, T, self.n_heads, self.head_dim).transpose(1, 2)
        k = k.view(B, T, self.n_heads, self.head_dim).transpose(1, 2)
        v = v.view(B, T, self.n_heads, self.head_dim).transpose(1, 2)

        att = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_dim)
        att = att.masked_fill(self.mask[:, :, :T, :T] == 0, float("-inf"))
        att = F.softmax(att, dim=-1)
        att = self.dropout(att)

        y = att @ v
        y = y.transpose(1, 2).contiguous().view(B, T, C)
        return self.dropout(self.proj(y))

class MLP(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(cfg.d_model, 4 * cfg.d_model),
            nn.GELU(),
            nn.Linear(4 * cfg.d_model, cfg.d_model),
            nn.Dropout(cfg.dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        self.ln1 = nn.LayerNorm(cfg.d_model)
        self.attn = CausalSelfAttention(cfg)
        self.ln2 = nn.LayerNorm(cfg.d_model)
        self.mlp = MLP(cfg)

    def forward(self, x):
        x = x + self.attn(self.ln1(x))
        x = x + self.mlp(self.ln2(x))
        return x

# === Step 5: Write the GPT class as one whole system ===

class GPT(nn.Module):
    def __init__(self, cfg, vocab_size):
        super().__init__()
        self.cfg = cfg
        self.token_embedding = nn.Embedding(vocab_size, cfg.d_model)
        self.position_embedding = nn.Embedding(cfg.block_size, cfg.d_model)
        self.blocks = nn.ModuleList([Block(cfg) for _ in range(cfg.n_layers)])
        self.ln_f = nn.LayerNorm(cfg.d_model)
        self.lm_head = nn.Linear(cfg.d_model, vocab_size, bias=False)

        # weight tying
        self.lm_head.weight = self.token_embedding.weight

        self.apply(self._init_weights)

self.lm_head.weight = self.token_embedding.weight

# === Step 6: Treat initialization as part of the model ===

def _init_weights(self, module):
    if isinstance(module, nn.Linear):
        nn.init.xavier_uniform_(module.weight)
        if module.bias is not None:
            nn.init.zeros_(module.bias)
    elif isinstance(module, nn.Embedding):
        nn.init.normal_(module.weight, mean=0.0, std=0.02)

# === Step 7: Write `forward()` so shapes stay honest ===

def forward(self, idx: torch.Tensor, targets: torch.Tensor = None) -> tuple:
    B, T = idx.shape
    assert T <= self.cfg.block_size

    pos = torch.arange(0, T, device=idx.device)
    x = self.token_embedding(idx) + self.position_embedding(pos)

    for block in self.blocks:
        x = block(x)

    x = self.ln_f(x)
    logits = self.lm_head(x)

    loss = None
    if targets is not None:
        B, T, V = logits.shape
        loss = F.cross_entropy(logits.view(B * T, V), targets.view(B * T))

    return logits, loss

# === Step 8: Write `generate()` for autoregressive sampling ===

@torch.no_grad()
def generate(self, idx: torch.Tensor, max_new_tokens: int, temperature: float = 1.0) -> torch.Tensor:
    for _ in range(max_new_tokens):
        idx_cond = idx[:, -self.cfg.block_size:]
        logits, _ = self(idx_cond)
        logits = logits[:, -1, :] / temperature
        probs = F.softmax(logits, dim=-1)
        next_idx = torch.multinomial(probs, num_samples=1)
        idx = torch.cat([idx, next_idx], dim=1)
    return idx

# === Step 9: Count parameters before and after weight tying ===

def count_params(model):
    return sum(p.numel() for p in model.parameters())

# === Step 10: Write the optimizer and your own learning rate schedule ===

def get_lr(step: int, cfg: 'Config') -> float:
    if step < cfg.warmup_steps:
        return cfg.learning_rate * (step + 1) / cfg.warmup_steps
    if step > cfg.max_steps:
        return cfg.min_lr
    decay_ratio = (step - cfg.warmup_steps) / (cfg.max_steps - cfg.warmup_steps)
    coeff = 0.5 * (1.0 + math.cos(math.pi * decay_ratio))
    return cfg.min_lr + coeff * (cfg.learning_rate - cfg.min_lr)

# === Step 11: Write the training loop yourself ===

import logging

model = GPT(cfg, vocab_size).to(cfg.device)
optimizer = torch.optim.AdamW(model.parameters(), lr=cfg.learning_rate)

for step in range(cfg.max_steps):
    lr = get_lr(step, cfg)
    for param_group in optimizer.param_groups:
        param_group["lr"] = lr

    xb, yb = get_batch("train", cfg)
    logits, loss = model(xb, yb)

    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)
    optimizer.step()

    if step % cfg.eval_interval == 0:
        train_loss = estimate_loss("train")
        val_loss = estimate_loss("val")
        logging.info("step %d  train_loss %.4f  val_loss %.4f", step, train_loss, val_loss)
        sample_text(model)
        save_checkpoint(...)

# === Step 12: Measure validation loss separately ===

@torch.no_grad()
def estimate_loss(split: str) -> float:
    model.eval()
    losses = torch.zeros(cfg.eval_steps)
    for k in range(cfg.eval_steps):
        xb, yb = get_batch(split, cfg)
        _, loss = model(xb, yb)
        losses[k] = loss.item()
    model.train()
    return losses.mean().item()

# === Step 14: Add checkpoint save/load before you need it ===

def save_checkpoint(path: str, model: 'GPT', optimizer, step: int, cfg: 'Config') -> None:
    torch.save({
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
        "step": step,
        "config": cfg.__dict__,
    }, path)

def load_checkpoint(path: str, model: 'GPT', optimizer) -> int:
    ckpt = torch.load(path, map_location=cfg.device)
    model.load_state_dict(ckpt["model"])
    optimizer.load_state_dict(ckpt["optimizer"])
    return ckpt["step"]
