"""
Project 1: The Learning Machine

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Build a Number That Remembers Where It Came From ===

x = 2.0
y = 3.0
z = x * y
print(z)  # 6.0

class Value:
    def __init__(self, data, _children=(), _op=''):
        self.data = data
        self.grad = 0.0
        self._prev = set(_children)
        self._op = _op
        self._backward = lambda: None

# === Step 2: Teach the Number How to Add ===

def __add__(self, other):
    other = other if isinstance(other, Value) else Value(other)
    out = Value(self.data + other.data, (self, other), '+')

    def _backward():
        self.grad += out.grad
        other.grad += out.grad

    out._backward = _backward
    return out

# === Step 3: Teach the Number How to Multiply ===

def __mul__(self, other):
    other = other if isinstance(other, Value) else Value(other)
    out = Value(self.data * other.data, (self, other), '*')

    def _backward():
        self.grad += other.data * out.grad
        other.grad += self.data * out.grad

    out._backward = _backward
    return out

# === Step 4: Add a Nonlinearity ===

import math

def tanh(self) -> 'Value':
    x = self.data
    t = (math.exp(2 * x) - 1) / (math.exp(2 * x) + 1)
    out = Value(t, (self,), 'tanh')

    def _backward():
        self.grad += (1 - out.data**2) * out.grad

    out._backward = _backward
    return out

# === Step 5: Build the Backward Pass ===

def backward(self):
    topo = []
    visited = set()

    def build_topo(v):
        if v not in visited:
            visited.add(v)
            for child in v._prev:
                build_topo(child)
            topo.append(v)

    build_topo(self)

    self.grad = 1.0
    for node in reversed(topo):
        node._backward()

# === Step 6: Add the Rest of the Small Operations ===

def __neg__(self):
    return self * -1

def __sub__(self, other):
    return self + (-other)

def __pow__(self, other):
    assert isinstance(other, (int, float))
    out = Value(self.data**other, (self,), f'**{other}')

    def _backward():
        self.grad += (other * self.data**(other - 1)) * out.grad

    out._backward = _backward
    return out

def __truediv__(self, other):
    return self * (other ** -1)

def exp(self):
    x = self.data
    out = Value(math.exp(x), (self,), 'exp')

    def _backward():
        self.grad += out.data * out.grad

    out._backward = _backward
    return out

def relu(self):
    out = Value(0 if self.data < 0 else self.data, (self,), 'ReLU')

    def _backward():
        self.grad += (out.data > 0) * out.grad

    out._backward = _backward
    return out

# === Step 7: Verify the Gradients Numerically ===

def finite_diff(f: callable, x: float, h: float = 1e-6) -> float:
    return (f(x + h) - f(x - h)) / (2 * h)

x = Value(0.7)
y = x.tanh()
y.backward()
print("autograd:", x.grad)

import math
fd = (math.tanh(0.7 + 1e-6) - math.tanh(0.7 - 1e-6)) / (2e-6)
print("finite diff:", fd)

# === Step 8: Build a Neuron ===

import random

class Neuron:
    def __init__(self, nin):
        self.w = [Value(random.uniform(-1, 1)) for _ in range(nin)]
        self.b = Value(0.0)

    def __call__(self, x):
        act = sum((wi * xi for wi, xi in zip(self.w, x)), self.b)
        out = act.tanh()
        return out

    def parameters(self):
        return self.w + [self.b]

# === Step 9: Build a Layer and an MLP ===

class Layer:
    def __init__(self, nin, nout):
        self.neurons = [Neuron(nin) for _ in range(nout)]

    def __call__(self, x):
        outs = [n(x) for n in self.neurons]
        return outs[0] if len(outs) == 1 else outs

    def parameters(self):
        return [p for n in self.neurons for p in n.parameters()]

class MLP:
    def __init__(self, nin, nouts):
        sz = [nin] + nouts
        self.layers = [Layer(sz[i], sz[i+1]) for i in range(len(nouts))]

    def __call__(self, x):
        for layer in self.layers:
            x = layer(x) if isinstance(x, list) else layer([x])
        return x

    def parameters(self):
        return [p for layer in self.layers for p in layer.parameters()]

# === Step 10: Create a Toy Dataset ===

xs = [
    [-1.2, -0.8],
    [-1.0, -1.1],
    [-0.8, -1.3],
    [1.0, 0.9],
    [1.2, 1.1],
    [0.8, 1.3],
]
ys = [-1, -1, -1, 1, 1, 1]

# === Step 11: Define the Loss ===

def loss_fn(model: 'MLP', xs: list, ys: list) -> tuple:
    preds = [model(x) for x in xs]
    loss = sum((pred - y)**2 for pred, y in zip(preds, ys))
    return loss, preds

# === Step 12: Run the Training Loop ===

for epoch in range(100):
    loss, preds = loss_fn(model, xs, ys)

    for p in model.parameters():
        p.grad = 0.0

    loss.backward()

    lr = 0.05
    for p in model.parameters():
        p.data -= lr * p.grad

    print(epoch, loss.data)

# === Step 13: Plot the Decision Boundary Over 100 Epochs ===

import numpy as np
import matplotlib.pyplot as plt

def plot_boundary(model, xs, ys, epoch):
    x_min, x_max = -2, 2
    y_min, y_max = -2, 2
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 200),
                         np.linspace(y_min, y_max, 200))

    zz = np.zeros_like(xx)
    for i in range(xx.shape[0]):
        for j in range(xx.shape[1]):
            zz[i, j] = model([float(xx[i, j]), float(yy[i, j])]).data

    plt.figure(figsize=(5, 5))
    plt.contourf(xx, yy, zz, levels=20, cmap='RdBu', alpha=0.6)
    plt.contour(xx, yy, zz, levels=[0], colors='black')

    for x, y in zip(xs, ys):
        color = 'red' if y == 1 else 'blue'
        plt.scatter(x[0], x[1], c=color, edgecolors='k')

    plt.title(f"epoch {epoch}")
    plt.xlim(x_min, x_max)
    plt.ylim(y_min, y_max)
    plt.show()
