"""
Project 29: Multimodal: A Tiny Vision-Language Model

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Build a tiny vision encoder ===

class PatchEmbed(nn.Module):
    def __init__(self, img_size=28, patch_size=4, in_chans=3, embed_dim=192):
        super().__init__()
        self.proj = nn.Conv2d(in_chans, embed_dim,
                              kernel_size=patch_size, stride=patch_size)
        self.num_patches = (img_size // patch_size) ** 2

    def forward(self, x):
        # x: (B, 3, 28, 28)
        x = self.proj(x)                  # (B, embed_dim, 7, 7)
        x = x.flatten(2).transpose(1, 2)  # (B, 49, embed_dim)
        return x

class TinyViT(nn.Module):
    def __init__(self, depth=4, embed_dim=192, num_heads=6,
                 img_size=28, patch_size=4):
        super().__init__()
        self.patch_embed = PatchEmbed(img_size, patch_size,
                                      in_chans=3, embed_dim=embed_dim)
        self.pos_embed = nn.Parameter(
            torch.zeros(1, self.patch_embed.num_patches, embed_dim))
        self.blocks = nn.ModuleList([
            ViTBlock(embed_dim, num_heads) for _ in range(depth)
        ])
        self.norm = nn.LayerNorm(embed_dim)

    def forward(self, x):
        x = self.patch_embed(x)
        x = x + self.pos_embed
        for blk in self.blocks:
            x = blk(x)
        return self.norm(x)

# === Step 2: Build the projection layer ===

class Projection(nn.Module):
    def __init__(self, vision_dim=192, text_dim=384):
        super().__init__()
        self.fc1 = nn.Linear(vision_dim, text_dim)
        self.act = nn.GELU()
        self.fc2 = nn.Linear(text_dim, text_dim)

    def forward(self, x):
        return self.fc2(self.act(self.fc1(x)))

# === Step 3: Extend the GPT input path to accept vision tokens ===

class GPT(nn.Module):
    def forward(self, idx=None, vision_embeds=None, targets=None):
        if vision_embeds is not None:
            # idx may still be present for the text portion
            text_embeds = self.tok_emb(idx) if idx is not None else None
            if text_embeds is not None:
                x = torch.cat([vision_embeds, text_embeds], dim=1)
            else:
                x = vision_embeds
        else:
            x = self.tok_emb(idx)

        T = x.shape[1]
        pos = self.pos_emb[:, :T, :]
        x = x + pos

        for blk in self.blocks:
            x = blk(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)

        if targets is not None:
            loss = F.cross_entropy(
                logits.view(-1, logits.size(-1)),
                targets.view(-1),
                ignore_index=-100,
            )
            return logits, loss
        return logits, None

# For a batch with 49 image tokens and a caption of length T:
# targets shape: (B, 49 + T)
# First 49 positions: -100 (ignored)
# Remaining T positions: shifted caption tokens, normal cross-entropy
targets[:, :49] = -100

# === Step 4: Pretrain on (image, caption) pairs ===

LABEL_TO_CAPTION = {
    0: "a photograph of an airplane.",
    1: "a photograph of an automobile.",
    2: "a photograph of a bird.",
    3: "a photograph of a cat.",
    4: "a photograph of a deer.",
    5: "a photograph of a dog.",
    6: "a photograph of a frog.",
    7: "a photograph of a horse.",
    8: "a photograph of a ship.",
    9: "a photograph of a truck.",
}

images, labels = next(loader)
captions = [LABEL_TO_CAPTION[y.item()] for y in labels]
input_ids, target_ids = encode_captions(captions, tokenizer)

vision_tokens = encoder(images)         # (B, 49, 192)
vision_embeds = projection(vision_tokens)  # (B, 49, 384)

# Pad targets with -100 in image positions
targets = pad_targets_with_image_mask(target_ids, num_image_tokens=49)

logits, loss = model(idx=input_ids,
                     vision_embeds=vision_embeds,
                     targets=targets)
loss.backward()
optimizer.step()

# === Step 5: Instruction-tune on visual question answering ===

VQA_TEMPLATES = {
    "dog": [
        ("What animal is in the picture?", "A dog."),
        ("Is this a cat or a dog?", "A dog."),
        ("Describe what you see.", "I see a dog."),
    ],
    # ... and so on
}

# === Step 6: Run inference ===

def caption(model, encoder, projection, image, tokenizer, max_new=20):
    model.eval()
    with torch.no_grad():
        # Encode the image
        vision_tokens = encoder(image.unsqueeze(0))
        vision_embeds = projection(vision_tokens)

        # Optional text prompt
        prompt_ids = tokenizer.encode("a photograph of")
        idx = torch.tensor([prompt_ids])

        # Generate
        for _ in range(max_new):
            logits, _ = model(idx=idx, vision_embeds=vision_embeds)
            next_id = logits[:, -1, :].argmax(dim=-1, keepdim=True)
            idx = torch.cat([idx, next_id], dim=1)
            if next_id.item() == tokenizer.eos_id:
                break

        return tokenizer.decode(idx[0].tolist())
