"""
Project 23: Reward Models And RLHF

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 2: Choose the Reward Model Architecture ===

score = w @ h_last + b

# === Step 10: Compare Step 0 and Step 10 Outputs by Hand ===

for prompts in dataloader:
    candidates = [policy.generate(prompts) for _ in range(G)]  # G samples per prompt
    rewards = reward_model.score(prompts, candidates)

    advantages = rewards - rewards.mean(dim=1, keepdim=True)

    logps = policy.logprob(prompts, candidates)

    loss = -(advantages.detach() * logps).mean()
    loss = loss + beta * kl_to_reference(policy, ref_policy, prompts)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
