"""
Project 10: Data Curation and Contamination

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Score the raw sample and see what is actually in there ===

from datasets import load_dataset
import re
from collections import Counter

ds = load_dataset("HuggingFaceFW/fineweb-edu",
                  name="sample-10BT", split="train", streaming=True)
sample = list(ds.take(100_000))

def doc_stats(text: str) -> dict:
    chars = len(text)
    tokens = text.split()
    n_tokens = len(tokens)
    mean_word_len = (sum(len(t) for t in tokens) / n_tokens
                     if n_tokens else 0.0)
    fives = [tuple(tokens[i:i+5]) for i in range(n_tokens - 4)]
    counts = Counter(fives)
    repeated = sum(c for c in counts.values() if c > 1)
    repetition = repeated / max(len(fives), 1)
    return {
        "chars": chars,
        "tokens": n_tokens,
        "mean_word_len": mean_word_len,
        "repetition": repetition,
    }

stats = [doc_stats(d["text"]) for d in sample]

# === Step 2: Build a MinHash deduper from scratch ===

import mmh3

def shingles(text: str, k: int = 5) -> set:
    tokens = text.split()
    if len(tokens) < k:
        return set()
    return {mmh3.hash64(" ".join(tokens[i:i+k]))[0]
            for i in range(len(tokens) - k + 1)}

import numpy as np

def minhash_signature(shingle_set: set, num_hashes: int = 128,
                      seed: int = 42) -> np.ndarray:
    if not shingle_set:
        return np.full(num_hashes, np.iinfo(np.uint64).max,
                       dtype=np.uint64)
    rng = np.random.default_rng(seed)
    # K independent hash functions implemented as (a*x + b) mod p
    p = (1 << 61) - 1
    a = rng.integers(1, p, size=num_hashes, dtype=np.uint64)
    b = rng.integers(0, p, size=num_hashes, dtype=np.uint64)
    shingles_arr = np.fromiter(shingle_set, dtype=np.uint64)
    # For each hash function, take the min over all shingles
    hashed = (np.outer(a, shingles_arr) + b[:, None]) % p
    return hashed.min(axis=1)

def lsh_buckets(signature: np.ndarray, num_bands: int = 32) -> list:
    bands = signature.reshape(num_bands, -1)
    return [mmh3.hash64(b.tobytes())[0] for b in bands]

# === Step 3: Compute 13-gram contamination against an eval set ===

def thirteen_grams(text: str) -> list:
    tokens = text.split()
    return [tuple(tokens[i:i+13]) for i in range(len(tokens) - 12)]

eval_index = {}
for eval_id, example in enumerate(eval_set):
    for gram in thirteen_grams(example["text"]):
        h = mmh3.hash64(" ".join(gram))[0]
        eval_index.setdefault(h, []).append(eval_id)

contaminated_docs = {}
for doc_id, doc in enumerate(training_corpus):
    hits = set()
    for gram in thirteen_grams(doc["text"]):
        h = mmh3.hash64(" ".join(gram))[0]
        if h in eval_index:
            hits.update(eval_index[h])
    if hits:
        contaminated_docs[doc_id] = hits

# === Step 4: Build a mixing weight schedule across three domains ===

def mixing_weights(step: int, total_steps: int) -> dict:
    progress = step / total_steps
    if progress < 0.8:
        return {"web": 0.85, "code": 0.10, "math": 0.05}
    # Ramp up code and math in the final 20%
    t = (progress - 0.8) / 0.2
    web = 0.85 - 0.30 * t
    code = 0.10 + 0.20 * t
    math = 0.05 + 0.10 * t
    return {"web": web, "code": code, "math": math}
