"""
Project 26: Tool Use and Function Calling

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Define a tool schema ===

TOOLS = [
    {
        "name": "get_weather",
        "description": "Look up the current weather for a city.",
        "parameters": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "description": "City name, e.g. 'Toronto'."
                }
            },
            "required": ["city"]
        }
    },
    {
        "name": "calculator",
        "description": "Evaluate a mathematical expression and return the result.",
        "parameters": {
            "type": "object",
            "properties": {
                "expression": {
                    "type": "string",
                    "description": "A Python-style math expression, e.g. '8347 * 91256'."
                }
            },
            "required": ["expression"]
        }
    }
]

# === Step 2: Generate synthetic tool-call training data ===

def make_weather_example(city):
    user = f"What is the weather in {city}?"
    assistant = (
        f"Thought: The user is asking about current weather. I should use get_weather.\n"
        f"Action: {{\"name\": \"get_weather\", \"arguments\": {{\"city\": \"{city}\"}}}}"
    )
    return {"user": user, "assistant": assistant}

def make_calc_example(a, b):
    user = f"What is {a} times {b}?"
    assistant = (
        f"Thought: The user is asking for a multiplication. I should use the calculator.\n"
        f"Action: {{\"name\": \"calculator\", \"arguments\": {{\"expression\": \"{a} * {b}\"}}}}"
    )
    return {"user": user, "assistant": assistant}

def make_no_tool_example(question, answer):
    user = question
    assistant = f"Thought: I can answer this from my own knowledge.\n{answer}"
    return {"user": user, "assistant": assistant}

# === Step 4: Build the tool runtime ===

import json
import re

def get_weather(city: str) -> str:
    # In real code, hit an API. In the lab, mock it.
    table = {"Toronto": "12C, light rain", "Tokyo": "22C, clear"}
    return table.get(city, f"Weather data unavailable for {city}.")

def calculator(expression: str) -> str:
    try:
        # eval() is only safe here because the lab is mocked.
        result = eval(expression, {"__builtins__": {}}, {})
        return str(result)
    except Exception as e:
        return f"ERROR: {e}"

REGISTRY = {"get_weather": get_weather, "calculator": calculator}

ACTION_PATTERN = re.compile(r"Action:\s*(\{.*\})", re.DOTALL)

def parse_action(text: str):
    match = ACTION_PATTERN.search(text)
    if not match:
        return None
    try:
        return json.loads(match.group(1))
    except json.JSONDecodeError:
        return None

def dispatch(action: dict) -> str:
    name = action.get("name")
    args = action.get("arguments", {})
    fn = REGISTRY.get(name)
    if fn is None:
        return f"ERROR: unknown tool '{name}'"
    try:
        return fn(**args)
    except TypeError as e:
        return f"ERROR: bad arguments: {e}"
    except Exception as e:
        return f"ERROR: tool raised: {e}"

# === Step 5: Implement the ReAct loop end-to-end ===

def run_react(model, tokenizer, user_question, max_steps=6):
    messages = [
        {"role": "system", "content": build_system_prompt(TOOLS)},
        {"role": "user", "content": user_question},
    ]
    for step in range(max_steps):
        response = model.generate_chat(messages)
        messages.append({"role": "assistant", "content": response})
        action = parse_action(response)
        if action is None:
            return response, messages
        observation = dispatch(action)
        messages.append({
            "role": "tool",
            "content": f"Observation: {observation}",
        })
    return response, messages

# === Step 8: Error handling, when the tool itself fails ===

def make_error_recovery_example():
    user = "What is the weather in Torronto?"  # typo
    turns = [
        ("assistant",
         "Thought: The user wants the weather. I'll try get_weather.\n"
         "Action: {\"name\": \"get_weather\", \"arguments\": {\"city\": \"Torronto\"}}"),
        ("tool",
         "Observation: ERROR: Weather data unavailable for Torronto."),
        ("assistant",
         "Thought: 'Torronto' looks like a typo for Toronto. I'll retry.\n"
         "Action: {\"name\": \"get_weather\", \"arguments\": {\"city\": \"Toronto\"}}"),
    ]
    return {"user": user, "turns": turns}
