"""
Project 17: Production Serving: Continuous Batching and PagedAttention

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Build the naive padded batcher ===

# inputs shape: (batch_size, max_prompt_len)
# kv_cache shape: (batch_size, max_seq_len, num_layers, num_heads, head_dim)

def naive_step(model, batch):
    # batch.tokens has shape (B, T), padded with PAD_TOKEN
    # batch.attention_mask has shape (B, T), 1 for real tokens, 0 for pad
    logits, batch.kv_cache = model(
        tokens=batch.tokens,
        attention_mask=batch.attention_mask,
        kv_cache=batch.kv_cache,
    )
    next_tokens = logits[:, -1, :].argmax(dim=-1)
    batch.tokens = torch.cat([batch.tokens, next_tokens.unsqueeze(-1)], dim=-1)
    batch.attention_mask = torch.cat(
        [batch.attention_mask, torch.ones_like(next_tokens).unsqueeze(-1)],
        dim=-1,
    )
    return batch

# === Step 2: Build the continuous batcher ===

@dataclass
class Request:
    request_id: int
    prompt_tokens: list[int]
    output_tokens: list[int]
    kv_cache: KVCacheHandle      # see Step 4 for paged version
    max_tokens: int
    finished: bool = False

class Scheduler:
    def __init__(self, model, max_batch_size):
        self.model = model
        self.max_batch_size = max_batch_size
        self.waiting: deque[Request] = deque()
        self.running: list[Request] = []

    def step(self):
        # 1. Retire finished requests
        self.running = [r for r in self.running if not r.finished]

        # 2. Admit new requests up to the batch capacity
        while len(self.running) < self.max_batch_size and self.waiting:
            new_req = self.waiting.popleft()
            self._prefill(new_req)
            self.running.append(new_req)

        # 3. One decode step over the running set
        if not self.running:
            return
        logits = self.model.decode_batch(self.running)
        next_tokens = logits.argmax(dim=-1)

        # 4. Append the new token to each request
        for req, tok in zip(self.running, next_tokens.tolist()):
            req.output_tokens.append(tok)
            if tok == EOS_TOKEN or len(req.output_tokens) >= req.max_tokens:
                req.finished = True

# === Step 4: Implement the paged KV cache ===

PAGE_SIZE = 16  # tokens per page

class BlockPool:
    def __init__(self, num_pages, page_shape, dtype, device):
        # one big tensor for all pages, indexed by physical page id
        self.storage = torch.zeros(
            (num_pages, *page_shape), dtype=dtype, device=device,
        )
        self.free_list: list[int] = list(range(num_pages))

    def alloc(self) -> int:
        if not self.free_list:
            raise OutOfPagesError()
        return self.free_list.pop()

    def free(self, page_id: int):
        self.free_list.append(page_id)

class PagedKVCache:
    def __init__(self, pool: BlockPool):
        self.pool = pool
        self.page_table: list[int] = []     # logical block -> physical page
        self.length: int = 0                # number of tokens stored

    def append(self, k: Tensor, v: Tensor):
        # k, v shapes: (num_layers, num_kv_heads, head_dim)
        slot_in_page = self.length % PAGE_SIZE
        if slot_in_page == 0:
            self.page_table.append(self.pool.alloc())
        page_id = self.page_table[-1]
        self.pool.storage[page_id, slot_in_page, :, :, 0] = k
        self.pool.storage[page_id, slot_in_page, :, :, 1] = v
        self.length += 1

    def free_all(self):
        for page_id in self.page_table:
            self.pool.free(page_id)
        self.page_table = []
        self.length = 0

# === Step 6: Implement attention over paged storage ===

def paged_attention(
    query: Tensor,                   # (num_heads, head_dim)
    page_table: list[int],           # logical_block -> physical_page
    block_pool_storage: Tensor,      # (num_pages, PAGE_SIZE, num_heads, head_dim, 2)
    seq_len: int,                    # number of tokens stored
) -> Tensor:
    out = torch.zeros_like(query)
    scores = torch.zeros(seq_len, device=query.device)

    for logical_block, physical_page in enumerate(page_table):
        page_start = logical_block * PAGE_SIZE
        page_end = min(page_start + PAGE_SIZE, seq_len)
        for t in range(page_start, page_end):
            slot = t - page_start
            k = block_pool_storage[physical_page, slot, :, :, 0]
            scores[t] = (query * k).sum() / math.sqrt(head_dim)

    weights = torch.softmax(scores[:seq_len], dim=-1)

    for logical_block, physical_page in enumerate(page_table):
        page_start = logical_block * PAGE_SIZE
        page_end = min(page_start + PAGE_SIZE, seq_len)
        for t in range(page_start, page_end):
            slot = t - page_start
            v = block_pool_storage[physical_page, slot, :, :, 1]
            out += weights[t] * v

    return out

# === Step 7: Simulate 100 concurrent users ===

def simulate(num_users, scheduler, duration_seconds):
    users = [User(scheduler) for _ in range(num_users)]
    start = time.time()
    total_tokens = 0
    latencies = []

    while time.time() - start < duration_seconds:
        # Each user submits a new request if it has none in flight
        for user in users:
            if user.in_flight is None:
                user.submit()

        # Run one scheduler step
        scheduler.step()

        # Collect finished requests
        for user in users:
            if user.in_flight and user.in_flight.finished:
                latencies.append(user.in_flight.latency())
                total_tokens += len(user.in_flight.output_tokens)
                user.in_flight = None

    return {
        "throughput_tokens_per_sec": total_tokens / duration_seconds,
        "p50_latency": np.percentile(latencies, 50),
        "p99_latency": np.percentile(latencies, 99),
    }

# === Step 8: Prefix caching ===

class PrefixCache:
    def __init__(self):
        self.cache: dict[tuple[int, ...], list[int]] = {}
        self.refcount: dict[int, int] = defaultdict(int)

    def find_prefix_match(self, tokens: list[int]) -> tuple[int, list[int]]:
        for n in range(len(tokens) // PAGE_SIZE * PAGE_SIZE, 0, -PAGE_SIZE):
            key = tuple(tokens[:n])
            if key in self.cache:
                pages = self.cache[key]
                for p in pages:
                    self.refcount[p] += 1
                return n, pages
        return 0, []
