"""
Project 15: Grouped Query Attention

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 2: Separate query head count from KV head count ===

self.n_head = 8

self.n_head = 8      # query heads
self.n_kv_head = 2   # shared key/value heads

self.group_size = self.n_head // self.n_kv_head

# === Step 3: Change the projection shapes ===

self.q_proj = nn.Linear(d_model, d_model, bias=False)
self.k_proj = nn.Linear(d_model, d_model, bias=False)
self.v_proj = nn.Linear(d_model, d_model, bias=False)

self.q_proj = nn.Linear(d_model, self.n_head * self.d_head, bias=False)
self.k_proj = nn.Linear(d_model, self.n_kv_head * self.d_head, bias=False)
self.v_proj = nn.Linear(d_model, self.n_kv_head * self.d_head, bias=False)
self.o_proj = nn.Linear(self.n_head * self.d_head, d_model, bias=False)

# === Step 4: Reshape queries, keys, and values separately ===

q = self.q_proj(x).view(B, T, self.n_head, self.d_head).transpose(1, 2)

k = self.k_proj(x).view(B, T, self.n_kv_head, self.d_head).transpose(1, 2)
v = self.v_proj(x).view(B, T, self.n_kv_head, self.d_head).transpose(1, 2)

# === Step 5: Expand shared K/V to match query heads ===

def repeat_kv(x: torch.Tensor, n_rep: int) -> torch.Tensor:
    B, H_kv, T, d_head = x.shape
    x = x[:, :, None, :, :].expand(B, H_kv, n_rep, T, d_head)
    return x.reshape(B, H_kv * n_rep, T, d_head)

k = repeat_kv(k, self.group_size)
v = repeat_kv(v, self.group_size)

# === Step 6: Apply attention the same way as before ===

att = (q @ k.transpose(-2, -1)) / math.sqrt(self.d_head)
att = att.masked_fill(self.bias[:, :, :T, :T] == 0, float('-inf'))
att = F.softmax(att, dim=-1)
y = att @ v

y = y.transpose(1, 2).contiguous().view(B, T, self.n_head * self.d_head)
y = self.o_proj(y)

# === Step 10: Keep the code mentally sorted into three layers ===

# x: (B, T, d_model)
q = self.q_proj(x).view(B, T, self.n_head, self.d_head).transpose(1, 2)
k = self.k_proj(x).view(B, T, self.n_kv_head, self.d_head).transpose(1, 2)
v = self.v_proj(x).view(B, T, self.n_kv_head, self.d_head).transpose(1, 2)

# Share each KV head across a group of query heads
k = repeat_kv(k, self.n_head // self.n_kv_head)
v = repeat_kv(v, self.n_head // self.n_kv_head)

# Standard scaled dot-product attention after shapes line up
att = (q @ k.transpose(-2, -1)) / math.sqrt(self.d_head)
att = att.masked_fill(causal_mask == 0, float('-inf'))
att = F.softmax(att, dim=-1)
y = att @ v
