"""
Project 31: Diffusion and Non-Autoregressive Decoding

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Load the mask predictor and locate the blank ===

import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModelForMaskedLM

MODEL = "bert-base-uncased"
tok = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForMaskedLM.from_pretrained(MODEL, dtype=torch.float32).eval()

MASK = tok.mask_token_id      # the integer id of the [MASK] blank
print("mask token:", tok.mask_token, "id:", MASK)

# === Step 2: Build the all-masked starting sequence ===

def build_sequence(prefix_text, n_blanks):
    prefix = tok(prefix_text, add_special_tokens=False)["input_ids"]
    ids = ([tok.cls_token_id] + prefix
           + [MASK] * n_blanks + [tok.sep_token_id])
    x = torch.tensor([ids])                       # shape (1, seq_len)
    start = 1 + len(prefix)                        # first blank position
    fill = torch.arange(start, start + n_blanks)   # positions we may fill
    return x, fill

x, fill = build_sequence("the weather today is", n_blanks=6)
print(tok.decode(x[0]))
# [CLS] the weather today is [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [SEP]

# === Step 3: One denoising step, and the confidence read ===

@torch.no_grad()
def predict(x, fill):
    logits = model(x).logits[0]              # (seq_len, vocab)
    probs = F.softmax(logits[fill], dim=-1)  # (n_blanks, vocab)
    conf, pred = probs.max(dim=-1)           # best prob + best token id
    return conf, pred                        # each shape (n_blanks,)

# === Step 4: The unmask schedule and the loop ===

@torch.no_grad()
def diffusion_decode(prefix_text, n_blanks, steps, verbose=True):
    x, fill = build_sequence(prefix_text, n_blanks)
    committed = torch.zeros(n_blanks, dtype=torch.bool)

    for s in range(steps):
        conf, pred = predict(x, fill)
        conf = conf.masked_fill(committed, -1.0)   # ignore filled blanks

        target = round(n_blanks * (s + 1) / steps)  # how many filled by now
        reveal = target - int(committed.sum())
        if reveal <= 0:
            continue

        order = torch.argsort(conf, descending=True)  # most confident first
        for j in order[:reveal]:
            x[0, fill[j]] = pred[j]     # write the token into the blank
            committed[j] = True         # mark it committed

        if verbose:
            filled = int(committed.sum())
            print(f"step {s+1:>2}/{steps}  filled {filled}/{n_blanks}  "
                  f"|  {tok.decode(x[0, fill])}")

    return tok.decode(x[0, fill])

out = diffusion_decode("the weather today is", n_blanks=6, steps=6)
