"""
Project 31: Layer Freezing and Transfer

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 3: Freeze parameters correctly ===

import torch

def freeze_bottom_layers(model: torch.nn.Module, freeze_ratio: float) -> int:
    n_layers = len(model.transformer.h)
    freeze_upto = int(n_layers * freeze_ratio)

    for layer_idx, block in enumerate(model.transformer.h):
        freeze = layer_idx < freeze_upto
        for p in block.parameters():
            p.requires_grad = not freeze

    return freeze_upto

import logging

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total = sum(p.numel() for p in model.parameters())
logging.info(f"trainable: {trainable}/{total} = {trainable/total:.2%}")

# === Step 6: Fine-tune each freeze configuration under matched conditions ===

trainable_params = [p for p in model.parameters() if p.requires_grad]
optimizer = torch.optim.AdamW(trainable_params, lr=lr, weight_decay=wd)

# === Step 9: Collect hidden states for CKA ===

with torch.no_grad():
    out_base = base_model(input_ids, output_hidden_states=True)
    out_ft = ft_model(input_ids, output_hidden_states=True)

base_hiddens = [h.reshape(-1, h.size(-1)) for h in out_base.hidden_states]
ft_hiddens = [h.reshape(-1, h.size(-1)) for h in out_ft.hidden_states]

import torch

def linear_cka(X: torch.Tensor, Y: torch.Tensor) -> float:
    X = X - X.mean(0, keepdim=True)
    Y = Y - Y.mean(0, keepdim=True)

    dot_xy = Y.T @ X
    dot_xx = X.T @ X
    dot_yy = Y.T @ Y

    num = (dot_xy ** 2).sum()
    den = torch.sqrt((dot_xx ** 2).sum() * (dot_yy ** 2).sum())
    return (num / den).item()
