"""
Project 6: From Prototype to nanoGPT

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 2: Compare embeddings ===

tok_emb = self.token_embedding(idx)      # (B, T, d)
pos = torch.arange(T, device=idx.device)
pos_emb = self.position_embedding(pos)   # (T, d)
x = tok_emb + pos_emb

# === Step 4: Compare transformer blocks ===

x = x + self.attn(self.ln1(x))
x = x + self.mlp(self.ln2(x))

# === Step 8: Compare batch construction and data path ===

ix = torch.randint(len(data) - block_size, (batch_size,))
x = torch.stack([data[i:i+block_size] for i in ix])
y = torch.stack([data[i+1:i+block_size+1] for i in ix])

# === Step 9: Compare optimizer setup ===

optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
