"""
Project 7: The Details That Matter

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Build LayerNorm from scratch ===

class LayerNorm(nn.Module):
    def __init__(self, d_model, eps=1e-5):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(d_model))   # gamma
        self.bias = nn.Parameter(torch.zeros(d_model))    # beta
        self.eps = eps

    def forward(self, x):
        mean = x.mean(dim=-1, keepdim=True)
        var = ((x - mean) ** 2).mean(dim=-1, keepdim=True)
        x_hat = (x - mean) / torch.sqrt(var + self.eps)
        return self.weight * x_hat + self.bias

# === Step 2: Build RMSNorm from scratch ===

class RMSNorm(nn.Module):
    def __init__(self, d_model, eps=1e-5):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(d_model))
        self.eps = eps

    def forward(self, x):
        rms = torch.sqrt((x ** 2).mean(dim=-1, keepdim=True) + self.eps)
        x_hat = x / rms
        return self.weight * x_hat

# === Step 3: Wire normalization into the transformer block ===

def make_norm(norm_type: str, d_model: int) -> nn.Module:
    if norm_type == "layernorm":
        return LayerNorm(d_model)
    if norm_type == "rmsnorm":
        return RMSNorm(d_model)
    if norm_type == "none":
        return nn.Identity()
    raise ValueError(f"unknown norm_type: {norm_type}")

self.norm1 = make_norm(config.norm_type, config.d_model)
self.norm2 = make_norm(config.norm_type, config.d_model)

x = x + self.attn(self.norm1(x))
x = x + self.mlp(self.norm2(x))

# === Step 4: Instrument hidden-state statistics ===

def tensor_stats(x: torch.Tensor) -> dict:
    flat = x.detach().float().reshape(-1)
    mean = flat.mean()
    var = flat.var(unbiased=False)
    std = torch.sqrt(var + 1e-12)
    centered = flat - mean
    kurt = (centered ** 4).mean() / (std ** 4 + 1e-12)

    return {
        "mean": mean.item(),
        "var": var.item(),
        "min": flat.min().item(),
        "max": flat.max().item(),
        "kurtosis": kurt.item(),
    }

if step % config.stats_every == 0:
    stats["block_03_pre_attn"] = tensor_stats(x)

# === Step 6: Build the activation functions ===

def gelu(x):
    return 0.5 * x * (1.0 + torch.tanh(
        math.sqrt(2.0 / math.pi) * (x + 0.044715 * x**3)
    ))

def relu2(x):
    return torch.relu(x) ** 2

class SwiGLU(nn.Module):
    def __init__(self, d_model, hidden_dim):
        super().__init__()
        self.w1 = nn.Linear(d_model, hidden_dim, bias=False)
        self.w2 = nn.Linear(d_model, hidden_dim, bias=False)
        self.w3 = nn.Linear(hidden_dim, d_model, bias=False)

    def forward(self, x):
        gate = F.silu(self.w1(x))
        value = self.w2(x)
        return self.w3(gate * value)

# === Step 7: Make the MLP activation configurable ===

class MLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        hidden = 4 * config.d_model

        if config.activation == "swiglu":
            self.kind = "swiglu"
            self.w1 = nn.Linear(config.d_model, hidden, bias=False)
            self.w2 = nn.Linear(config.d_model, hidden, bias=False)
            self.w3 = nn.Linear(hidden, config.d_model, bias=False)
        else:
            self.kind = config.activation
            self.fc1 = nn.Linear(config.d_model, hidden)
            self.fc2 = nn.Linear(hidden, config.d_model)

    def forward(self, x):
        if self.kind == "gelu":
            return self.fc2(gelu(self.fc1(x)))
        if self.kind == "relu2":
            return self.fc2(torch.relu(self.fc1(x)) ** 2)
        if self.kind == "swiglu":
            return self.w3(F.silu(self.w1(x)) * self.w2(x))
        raise ValueError(self.kind)

# === Step 8: Replace learned positional embeddings with RoPE ===

x = tok_emb[idx] + pos_emb[pos]

def rotate_half(x):
    x1 = x[..., ::2]
    x2 = x[..., 1::2]
    return torch.stack((-x2, x1), dim=-1).flatten(-2)

def apply_rope(x, cos, sin):
    return (x * cos) + (rotate_half(x) * sin)

def build_rope_cache(seq_len: int, head_dim: int, device, base: int = 10000) -> tuple:
    half_dim = head_dim // 2
    freq_seq = torch.arange(half_dim, device=device).float()
    inv_freq = 1.0 / (base ** (freq_seq / half_dim))

    positions = torch.arange(seq_len, device=device).float()
    angles = torch.outer(positions, inv_freq)  # (T, head_dim/2)

    cos = torch.cos(angles).repeat_interleave(2, dim=-1)  # (T, head_dim)
    sin = torch.sin(angles).repeat_interleave(2, dim=-1)
    return cos[None, None, :, :], sin[None, None, :, :]

cos, sin = build_rope_cache(T, head_dim, x.device)
q = apply_rope(q, cos, sin)
k = apply_rope(k, cos, sin)
