"""
Project 2: Predicting The Next Character

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 2: Build the vocabulary ===

chars = sorted(list(set(text)))
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for ch, i in stoi.items()}

chars = ['.'] + sorted(list(set(text.replace('\n', ''))))
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for ch, i in stoi.items()}

# === Step 3: Bigram counts ===

import torch

N = torch.zeros((V, V), dtype=torch.int32)

for word in words:
    chs = ['.'] + list(word) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        i = stoi[ch1]
        j = stoi[ch2]
        N[i, j] += 1

# === Step 4: Turn counts into probabilities ===

P = N.float()
P = P / P.sum(dim=1, keepdim=True)

P = (N + 1).float()
P = P / P.sum(dim=1, keepdim=True)

# === Step 5: Sample from the bigram model ===

g = torch.Generator().manual_seed(42)

ix = stoi['.']
out = []

while True:
    probs = P[ix]
    ix = torch.multinomial(probs, num_samples=1, replacement=True, generator=g).item()
    ch = itos[ix]
    if ch == '.':
        break
    out.append(ch)

print(''.join(out))

# === Step 6: Measure negative log-likelihood for the bigram model ===

log_likelihood = 0.0
n = 0

for word in words:
    chs = ['.'] + list(word) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        i = stoi[ch1]
        j = stoi[ch2]
        prob = P[i, j]
        log_likelihood += torch.log(prob)
        n += 1

nll = -log_likelihood / n
print(nll.item())
