"""
Project 35: Your Architecture

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 5: Decide where the architecture change lives ===

# x: anchor or task batch
# base_model: frozen reference
# specialist: trainable model or adapter
# lambda_interface: strength of interface preservation

task_loss = specialist.task_loss(task_batch)

with torch.no_grad():
    base_h = base_model.forward(anchor_batch, return_hidden=True)

spec_h = specialist.forward(anchor_batch, return_hidden=True)

interface_loss = mse(spec_h[layer_id], base_h[layer_id])

loss = task_loss + lambda_interface * interface_loss
loss.backward()
