"""
Project 11: Training Debugging: Spikes, NaNs, and Profiling

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Add per-layer gradient norm logging ===

def group_grad_norms(model):
    norms = {}
    for name, module in model.named_modules():
        params = [p for p in module.parameters(recurse=False)
                  if p.grad is not None]
        if not params:
            continue
        total_sq = sum((p.grad ** 2).sum().item() for p in params)
        norms[name] = total_sq ** 0.5
    return norms

# === Step 2: Add per-layer activation histogram ===

activation_stats = {}

def make_hook(name):
    def hook(module, inputs, output):
        x = output.detach().float()
        activation_stats[name] = {
            "mean": x.mean().item(),
            "std": x.std().item(),
            "min": x.min().item(),
            "max": x.max().item(),
            "abs_max": x.abs().max().item(),
        }
    return hook

for name, module in model.named_modules():
    if isinstance(module, TransformerBlock):
        module.register_forward_hook(make_hook(name))

# === Step 3: Add weight-update ratio ===

def update_ratios(model, optimizer_step):
    pre_norms = {}
    pre_params = {}
    for name, p in model.named_parameters():
        if p.requires_grad:
            pre_norms[name] = p.data.norm().item()
            pre_params[name] = p.data.clone()
    optimizer_step()
    ratios = {}
    for name, p in model.named_parameters():
        if p.requires_grad and pre_norms[name] > 0:
            delta = (p.data - pre_params[name]).norm().item()
            ratios[name] = delta / pre_norms[name]
    return ratios

# === Step 6: Apply gradient clipping and watch the spike absorbed ===

torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

# === Step 7: Mixed-precision overflow detection ===

scaler = torch.cuda.amp.GradScaler()
overflow_count = 0
step_count = 0

# Inside the training loop:
scaler.scale(loss).backward()
prev_scale = scaler.get_scale()
scaler.step(optimizer)
scaler.update()
if scaler.get_scale() < prev_scale:
    overflow_count += 1
step_count += 1
