"""
Project 30: Non-Transformer Architectures (Mamba, RWKV)

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: A minimal selective SSM block ===

import torch
import torch.nn as nn

class S6Block(nn.Module):
    def __init__(self, d_model: int, d_state: int = 16):
        super().__init__()
        self.d_model = d_model
        self.d_state = d_state

        # A is stored as log(-A) so A stays negative when exponentiated.
        # Negative real A means the recurrence is stable.
        A = torch.arange(1, d_state + 1).float().expand(d_model, d_state)
        self.A_log = nn.Parameter(torch.log(A))

        # Input-dependent projections: B, C, and the step size delta
        # are all produced from x by a linear layer.
        self.x_proj = nn.Linear(d_model, d_state * 2 + 1, bias=False)

        # The step size delta also gets a learned bias before softplus.
        self.dt_proj = nn.Linear(1, d_model)

        # Skip-connection multiplier (per channel).
        self.D = nn.Parameter(torch.ones(d_model))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, L, D = x.shape
        N = self.d_state

        # Project x into B, C, and delta.
        x_proj = self.x_proj(x)              # (B, L, 2N + 1)
        B_in, C_in, dt = x_proj.split(
            [N, N, 1], dim=-1)
        dt = torch.nn.functional.softplus(
            self.dt_proj(dt))                # (B, L, D)

        A = -torch.exp(self.A_log)           # (D, N), all negative

        # Discretize: A_bar = exp(dt * A), B_bar approximation
        # collapses to dt * B for small dt.
        A_bar = torch.exp(dt.unsqueeze(-1) * A)   # (B, L, D, N)
        B_bar = dt.unsqueeze(-1) * B_in.unsqueeze(-2)  # (B, L, D, N)

        # Recurrence: walk through the sequence one step at a time.
        s = torch.zeros(B, D, N, device=x.device)
        ys = []
        for t in range(L):
            s = A_bar[:, t] * s + B_bar[:, t] * x[:, t].unsqueeze(-1)
            y = (C_in[:, t].unsqueeze(1) * s).sum(-1)   # (B, D)
            ys.append(y)
        y = torch.stack(ys, dim=1)            # (B, L, D)

        # The D parameter is a residual skip: a direct linear path
        # from input to output, in parallel with the SSM.
        return y + self.D * x

# === Step 2: Wire the SSM into a Project-5 model ===

class SSMBlock(nn.Module):
    def __init__(self, d_model: int, d_state: int = 16, d_ff: int = None):
        super().__init__()
        d_ff = d_ff or 4 * d_model
        self.norm1 = nn.RMSNorm(d_model)
        self.ssm = S6Block(d_model, d_state)
        self.norm2 = nn.RMSNorm(d_model)
        self.mlp = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.GELU(),
            nn.Linear(d_ff, d_model),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x + self.ssm(self.norm1(x))
        x = x + self.mlp(self.norm2(x))
        return x

# === Step 4: A minimal RWKV time-mix block ===

class RWKVTimeMix(nn.Module):
    def __init__(self, d_model: int):
        super().__init__()
        self.d_model = d_model
        # Per-channel decay rate, kept positive via softplus.
        self.w_raw = nn.Parameter(torch.zeros(d_model))
        # Per-channel projections.
        self.key = nn.Linear(d_model, d_model, bias=False)
        self.value = nn.Linear(d_model, d_model, bias=False)
        self.receptance = nn.Linear(d_model, d_model, bias=False)
        self.output = nn.Linear(d_model, d_model, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, L, D = x.shape
        w = torch.nn.functional.softplus(self.w_raw)   # (D,)
        decay = torch.exp(-w)                          # (D,)

        k = self.key(x)        # (B, L, D)
        v = self.value(x)      # (B, L, D)
        r = torch.sigmoid(self.receptance(x))  # (B, L, D)

        num = torch.zeros(B, D, device=x.device)
        den = torch.zeros(B, D, device=x.device) + 1e-8
        outs = []
        for t in range(L):
            kt = k[:, t]
            vt = v[:, t]
            num = decay * num + torch.exp(kt) * vt
            den = decay * den + torch.exp(kt)
            wkv = num / den
            outs.append(r[:, t] * wkv)
        out = torch.stack(outs, dim=1)        # (B, L, D)
        return self.output(out)

class ChannelMix(nn.Module):
    def __init__(self, d_model: int, d_ff: int = None):
        super().__init__()
        d_ff = d_ff or 4 * d_model
        self.key = nn.Linear(d_model, d_ff, bias=False)
        self.value = nn.Linear(d_ff, d_model, bias=False)
        self.receptance = nn.Linear(d_model, d_model, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        k = torch.relu(self.key(x)) ** 2     # squared ReLU
        v = self.value(k)
        r = torch.sigmoid(self.receptance(x))
        return r * v

# === Step 5: Train RWKV on the same data ===

class RWKVBlock(nn.Module):
    def __init__(self, d_model: int):
        super().__init__()
        self.norm1 = nn.RMSNorm(d_model)
        self.tm = RWKVTimeMix(d_model)
        self.norm2 = nn.RMSNorm(d_model)
        self.cm = ChannelMix(d_model)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x + self.tm(self.norm1(x))
        x = x + self.cm(self.norm2(x))
        return x
