"""
Project 28: Retrieval-Augmented Generation

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Train a small sentence-embedding model with contrastive loss ===

def info_nce_loss(query_embs, passage_embs, tau=0.07):
    sim = query_embs @ passage_embs.T / tau
    labels = torch.arange(sim.size(0), device=sim.device)
    return F.cross_entropy(sim, labels)

# === Step 2: Build a FAISS index over a 10K-document corpus ===

import faiss
import numpy as np

doc_vectors = encode_documents(corpus)
doc_vectors = doc_vectors / np.linalg.norm(doc_vectors, axis=1, keepdims=True)
index = faiss.IndexFlatIP(doc_vectors.shape[1])
index.add(doc_vectors.astype(np.float32))

# === Step 3: Implement retrieval end-to-end ===

def retrieve(query, encoder, index, corpus, k=5):
    q_vec = encoder.encode([query])
    q_vec = q_vec / np.linalg.norm(q_vec)
    scores, ids = index.search(q_vec.astype(np.float32), k)
    return [(corpus[i], float(s)) for i, s in zip(ids[0], scores[0])]

# === Step 6: Add a cross-encoder re-ranker ===

def retrieve_and_rerank(query, encoder, reranker, index, corpus, k_recall=50, k_final=3):
    q_vec = encoder.encode([query])
    q_vec = q_vec / np.linalg.norm(q_vec)
    _, ids = index.search(q_vec.astype(np.float32), k_recall)
    candidates = [corpus[i] for i in ids[0]]
    pairs = [(query, doc) for doc in candidates]
    scores = reranker.predict(pairs)
    top_idx = np.argsort(-scores)[:k_final]
    return [candidates[i] for i in top_idx]
