"""
Project 19: Scaling Laws

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 5: Plot loss versus parameter count on log axes ===

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("scaling_runs.csv")  # columns: depth, params, val_loss
plt.scatter(df["params"], df["val_loss"])
plt.xscale("log")
plt.xlabel("Parameter count")
plt.ylabel("Final validation loss")
plt.show()

# === Step 6: Fit the scaling law ===

import numpy as np
import pandas as pd

df = pd.read_csv("scaling_runs.csv")
x = np.log(df["params"].to_numpy())
y = np.log(df["val_loss"].to_numpy())

slope, intercept = np.polyfit(x, y, 1)
b = -slope
a = np.exp(intercept)

print("a =", a)
print("b =", b)

# === Step 7: Extrapolate to a target, such as GPT-2-level loss ===

L_target = 2.85  # example only
P_needed = (a / L_target) ** (1 / b)
print("Predicted parameters:", int(P_needed))

# === Step 8: Build the cost calculator ===

def train_time_hours(params: int, tokens_per_second: float, tokens_per_param: int = 8) -> float:
    target_tokens = tokens_per_param * params
    seconds = target_tokens / tokens_per_second
    return seconds / 3600

print(train_time_hours(params=200_000_000, tokens_per_second=40_000))
