"""
Project 14: Speculative Decoding

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Train a tiny draft model on the same data ===

def measure_tokens_per_second(model, prompt_ids, num_tokens=128):
    model.eval()
    start = time.time()
    ids = prompt_ids.clone()
    with torch.no_grad():
        for _ in range(num_tokens):
            logits = model(ids)[:, -1, :]
            next_id = torch.argmax(logits, dim=-1, keepdim=True)
            ids = torch.cat([ids, next_id], dim=1)
    elapsed = time.time() - start
    return num_tokens / elapsed

# === Step 2: Naive draft generation of K=4 tokens ===

def draft_propose(draft_model, ids, K=4):
    candidate_ids = []
    candidate_qs = []
    cur = ids.clone()
    for _ in range(K):
        with torch.no_grad():
            logits = draft_model(cur)[:, -1, :]
            probs = torch.softmax(logits, dim=-1)
            next_id = torch.multinomial(probs, num_samples=1)
            q = probs.gather(-1, next_id)
        candidate_ids.append(next_id)
        candidate_qs.append((probs, next_id))  # store full dist for residual
        cur = torch.cat([cur, next_id], dim=1)
    return torch.cat(candidate_ids, dim=1), candidate_qs

# === Step 3: Parallel verification on the main model ===

def main_verify(main_model, ids, candidate_ids):
    full_seq = torch.cat([ids, candidate_ids], dim=1)
    with torch.no_grad():
        logits = main_model(full_seq)
    K = candidate_ids.shape[1]
    # We want the main model's distribution at the K positions where
    # the draft proposed tokens. If candidate token t_i was proposed
    # at position len(ids)+i, then the main model's distribution for
    # that position is at logits[:, len(ids)+i-1, :], because the
    # output at position j predicts the token at position j+1.
    main_dists = []
    start = ids.shape[1] - 1
    for i in range(K):
        p_logits = logits[:, start + i, :]
        main_dists.append(torch.softmax(p_logits, dim=-1))
    # The +1 distribution (after the last candidate) is the bonus
    # distribution we sample from if all K candidates are accepted.
    bonus_dist = torch.softmax(logits[:, start + K, :], dim=-1)
    return main_dists, bonus_dist

# === Step 4: The acceptance rule and the residual distribution, walked through ===

def speculative_step(draft_model, main_model, ids, K=4):
    candidate_ids, draft_dists = draft_propose(draft_model, ids, K)
    main_dists, bonus_dist = main_verify(main_model, ids, candidate_ids)

    accepted_ids = []
    for i in range(K):
        t = candidate_ids[:, i:i+1]
        q_full, _ = draft_dists[i]
        p_full = main_dists[i]
        q_t = q_full.gather(-1, t)
        p_t = p_full.gather(-1, t)
        u = torch.rand_like(q_t)
        if (u < torch.clamp(p_t / q_t, max=1.0)).all():
            accepted_ids.append(t)
        else:
            # Residual distribution: max(0, p - q), normalized.
            residual = torch.clamp(p_full - q_full, min=0.0)
            residual = residual / residual.sum(dim=-1, keepdim=True)
            replacement = torch.multinomial(residual, num_samples=1)
            accepted_ids.append(replacement)
            return torch.cat(accepted_ids, dim=1)

    # All K accepted: append the bonus token from the main model.
    bonus = torch.multinomial(bonus_dist, num_samples=1)
    accepted_ids.append(bonus)
    return torch.cat(accepted_ids, dim=1)

# === Step 5: Measure speedup against naive KV-cached generation ===

def measure_speculative_tps(draft, main, prompt, K=4, total=256):
    ids = prompt.clone()
    accepted_total = 0
    rounds = 0
    start = time.time()
    while ids.shape[1] - prompt.shape[1] < total:
        new_ids = speculative_step(draft, main, ids, K=K)
        ids = torch.cat([ids, new_ids], dim=1)
        accepted_total += new_ids.shape[1] - 1  # exclude the bonus/residual
        rounds += 1
    elapsed = time.time() - start
    accept_rate = accepted_total / (rounds * K)
    return total / elapsed, accept_rate

# === Step 6: Sweep K from 1 to 8 and find the sweet spot ===

results = {}
for K in [1, 2, 3, 4, 5, 6, 7, 8]:
    tps, accept = measure_speculative_tps(draft, main, prompt, K=K, total=512)
    results[K] = (tps, accept)
    print(f"K={K}: {tps:.1f} tokens/sec, acceptance rate {accept:.3f}")

# === Step 7: Medusa — drafting from the main model itself ===

class MedusaHead(nn.Module):
    def __init__(self, d_model, vocab_size, depth=1):
        super().__init__()
        # A small residual MLP on top of the main hidden state.
        layers = []
        for _ in range(depth):
            layers.append(nn.Linear(d_model, d_model))
            layers.append(nn.SiLU())
        layers.append(nn.Linear(d_model, vocab_size))
        self.net = nn.Sequential(*layers)

    def forward(self, h):
        return self.net(h)
