"""
Project 8: Flash Attention and Tiled Kernels

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Measure where the naive version dies ===

def naive_attention(q, k, v):
    # q, k, v: (batch, heads, seq, dim)
    d = q.shape[-1]
    scores = (q @ k.transpose(-2, -1)) / (d ** 0.5)   # (B, H, N, N)
    weights = torch.softmax(scores, dim=-1)            # (B, H, N, N)
    return weights @ v                                  # (B, H, N, D)

import torch

def measure_naive(seq_lens, batch=2, heads=8, dim=64, device="cuda", dtype=torch.float16):
    results = {}
    for n in seq_lens:
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()
        q = torch.randn(batch, heads, n, dim, device=device, dtype=dtype)
        k = torch.randn_like(q)
        v = torch.randn_like(q)
        try:
            out = naive_attention(q, k, v)
            torch.cuda.synchronize()
            peak = torch.cuda.max_memory_allocated() / 1e9
            results[n] = peak
        except torch.cuda.OutOfMemoryError:
            results[n] = None
        del q, k, v
        if results[n] is not None:
            del out
    return results

print(measure_naive([1024, 2048, 4096, 8192]))

# === Step 2: Decompose the computation into tiles ===

BR = 64   # query row tile size
BC = 64   # key/value column tile size

def tiled_attention_skeleton(q, k, v, BR=64, BC=64):
    B, H, N, D = q.shape
    out = torch.zeros_like(q)

    for i in range(0, N, BR):
        q_tile = q[:, :, i:i+BR, :]                   # (B, H, BR, D)
        # running statistics for this query row tile, set up in Step 3
        for j in range(0, N, BC):
            k_tile = k[:, :, j:j+BC, :]               # (B, H, BC, D)
            v_tile = v[:, :, j:j+BC, :]               # (B, H, BC, D)
            scores_tile = q_tile @ k_tile.transpose(-2, -1)  # (B, H, BR, BC)
            # update running statistics and partial output using scores_tile
            ...
        # write final row tile of out
        out[:, :, i:i+BR, :] = ...
    return out

# === Step 3: Build the streaming softmax ===

m_tile = s_tile.max(dim=-1, keepdim=True).values     # local max of the tile
p_tile = torch.exp(s_tile - m_tile)                  # local stable exponentials
l_tile = p_tile.sum(dim=-1, keepdim=True)            # local sum of exponentials

m_new = torch.maximum(m_running, m_tile)
alpha = torch.exp(m_running - m_new)                 # rescaling for old stats
beta  = torch.exp(m_tile    - m_new)                 # rescaling for tile stats
l_new = alpha * l_running + beta * l_tile
o_new = alpha * o_running + beta * (p_tile @ v_tile)
m_running, l_running, o_running = m_new, l_new, o_new

o_final = o_running / l_running

def tiled_attention(q, k, v, BR=64, BC=64, causal=False):
    B, H, N, D = q.shape
    scale = D ** -0.5
    out = torch.zeros_like(q)

    for i in range(0, N, BR):
        q_tile = q[:, :, i:i+BR, :]
        m = torch.full((B, H, q_tile.shape[2], 1), float("-inf"),
                       device=q.device, dtype=q.dtype)
        l = torch.zeros((B, H, q_tile.shape[2], 1),
                        device=q.device, dtype=q.dtype)
        o = torch.zeros_like(q_tile)

        for j in range(0, N, BC):
            k_tile = k[:, :, j:j+BC, :]
            v_tile = v[:, :, j:j+BC, :]

            s = (q_tile @ k_tile.transpose(-2, -1)) * scale
            if causal:
                # mask future positions inside this tile
                row_idx = torch.arange(i, i + q_tile.shape[2], device=q.device)[:, None]
                col_idx = torch.arange(j, j + k_tile.shape[2], device=q.device)[None, :]
                s = s.masked_fill(col_idx > row_idx, float("-inf"))

            m_tile = s.max(dim=-1, keepdim=True).values
            p = torch.exp(s - m_tile)
            l_tile = p.sum(dim=-1, keepdim=True)

            m_new = torch.maximum(m, m_tile)
            alpha = torch.exp(m - m_new)
            beta = torch.exp(m_tile - m_new)
            l = alpha * l + beta * l_tile
            o = alpha * o + beta * (p @ v_tile)
            m = m_new

        out[:, :, i:i+BR, :] = o / l

    return out

# === Step 4: Verify against the naive version ===

torch.manual_seed(0)
B, H, N, D = 2, 4, 256, 32
q = torch.randn(B, H, N, D, device="cuda")
k = torch.randn(B, H, N, D, device="cuda")
v = torch.randn(B, H, N, D, device="cuda")

ref = naive_attention(q, k, v)
out = tiled_attention(q, k, v, BR=32, BC=32)

diff = (ref - out).abs().max().item()
print(f"max absolute difference: {diff:.6e}")

# === Step 5: Measure memory versus the naive version ===

def measure_tiled(seq_lens, batch=2, heads=8, dim=64, device="cuda", dtype=torch.float16):
    results = {}
    for n in seq_lens:
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()
        q = torch.randn(batch, heads, n, dim, device=device, dtype=dtype)
        k = torch.randn_like(q)
        v = torch.randn_like(q)
        out = tiled_attention(q, k, v, BR=64, BC=64)
        torch.cuda.synchronize()
        results[n] = torch.cuda.max_memory_allocated() / 1e9
        del q, k, v, out
    return results

print(measure_tiled([1024, 2048, 4096, 8192, 16384, 32768]))

# === Step 7: Benchmark wall-clock ===

import time

def bench(fn, q, k, v, repeats=10):
    for _ in range(3):  # warmup
        fn(q, k, v)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(repeats):
        fn(q, k, v)
    torch.cuda.synchronize()
    return (time.perf_counter() - t0) / repeats
