"""
Project 24: DPO and Preference Optimization

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Prepare a preference-pair dataset ===

from datasets import load_dataset

dataset = load_dataset("openbmb/UltraFeedback", split="train")
print(dataset[0])

def to_preference_pair(example):
    completions = example["completions"]
    scored = sorted(completions, key=lambda c: c["overall_score"], reverse=True)
    return {
        "prompt": example["instruction"],
        "chosen": scored[0]["response"],
        "rejected": scored[-1]["response"],
    }

paired = dataset.map(to_preference_pair, remove_columns=dataset.column_names)

def format_pair(example, tokenizer):
    chat = [{"role": "user", "content": example["prompt"]}]
    formatted_prompt = tokenizer.apply_chat_template(chat, tokenize=False)
    return {
        "prompt": formatted_prompt,
        "chosen": formatted_prompt + example["chosen"],
        "rejected": formatted_prompt + example["rejected"],
    }

# === Step 2: Write the DPO loss directly from the paper ===

def dpo_loss(policy_chosen_logps, policy_rejected_logps,
             ref_chosen_logps, ref_rejected_logps, beta=0.1):
    pi_logratios = policy_chosen_logps - policy_rejected_logps
    ref_logratios = ref_chosen_logps - ref_rejected_logps
    logits = beta * (pi_logratios - ref_logratios)
    loss = -F.logsigmoid(logits).mean()
    return loss

# === Step 3: Fine-tune the SFT model with DPO ===

for batch in train_loader:
    prompt_ids, chosen_ids, rejected_ids = batch

    # Forward pass through policy (trains)
    policy_chosen_logps = compute_logprobs(policy, prompt_ids, chosen_ids)
    policy_rejected_logps = compute_logprobs(policy, prompt_ids, rejected_ids)

    # Forward pass through reference (no grad)
    with torch.no_grad():
        ref_chosen_logps = compute_logprobs(ref_model, prompt_ids, chosen_ids)
        ref_rejected_logps = compute_logprobs(ref_model, prompt_ids, rejected_ids)

    loss = dpo_loss(policy_chosen_logps, policy_rejected_logps,
                    ref_chosen_logps, ref_rejected_logps, beta=0.1)

    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

def compute_logprobs(model, prompt_ids, completion_ids):
    full_ids = torch.cat([prompt_ids, completion_ids], dim=-1)
    logits = model(full_ids).logits[:, :-1]  # next-token logits
    targets = full_ids[:, 1:]
    logprobs = F.log_softmax(logits, dim=-1)
    token_logprobs = logprobs.gather(-1, targets.unsqueeze(-1)).squeeze(-1)
    # Mask out prompt tokens
    completion_mask = torch.zeros_like(targets, dtype=torch.bool)
    completion_mask[:, prompt_ids.size(-1) - 1:] = True
    return (token_logprobs * completion_mask).sum(dim=-1)

# === Step 5: Implement KTO ===

def kto_loss(policy_logps, ref_logps, label, beta=0.1, desirable_weight=1.0, undesirable_weight=1.0):
    # Implicit reward
    logratio = policy_logps - ref_logps

    # Baseline: KL divergence estimate from a mismatched batch
    # (computed elsewhere; here we just use the mean as a stand-in)
    kl_baseline = compute_kl_baseline(policy, ref_model)

    if label == "desirable":
        loss = desirable_weight * (1 - torch.sigmoid(beta * (logratio - kl_baseline)))
    else:  # undesirable
        loss = undesirable_weight * (1 - torch.sigmoid(beta * (kl_baseline - logratio)))

    return loss.mean()

# === Step 6: Implement ORPO ===

def orpo_loss(policy_chosen_logps, policy_rejected_logps, chosen_labels, lambda_=0.1):
    # SFT term: standard negative log-likelihood on chosen
    nll_loss = -policy_chosen_logps.mean()

    # Odds ratio term
    log_odds = (policy_chosen_logps - torch.log(1 - torch.exp(policy_chosen_logps))) \
             - (policy_rejected_logps - torch.log(1 - torch.exp(policy_rejected_logps)))
    or_loss = -F.logsigmoid(log_odds).mean()

    return nll_loss + lambda_ * or_loss

# === Step 7: Implement SimPO ===

def simpo_loss(policy_chosen_logps, policy_rejected_logps,
               chosen_lens, rejected_lens, beta=2.0, gamma=1.0):
    # Length-normalized log-probs
    chosen_avg_logps = policy_chosen_logps / chosen_lens
    rejected_avg_logps = policy_rejected_logps / rejected_lens

    # Target reward margin
    logits = beta * (chosen_avg_logps - rejected_avg_logps) - gamma

    loss = -F.logsigmoid(logits).mean()
    return loss
