"""
Project 20: Autonomous Experimentation

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 8: Write your own `program.md` ===

if new_val_bpb < best_val_bpb:
    keep_change()
else:
    discard_change()

if new_memory_gb < best_memory_gb and new_val_bpb <= baseline_val_bpb + 0.005:
    keep_change()
else:
    discard_change()
