"""
Project 25: Test-Time Reasoning (CoT, Self-Consistency, Best-of-N)

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Direct prompting and CoT prompting on GSM8K ===

def run_one(prompt, max_new_tokens=256, temperature=0.0):
    out = model.generate(prompt, max_new_tokens=max_new_tokens,
                         temperature=temperature, do_sample=temperature > 0)
    return out

def extract_answer(text):
    nums = re.findall(r"-?\d+\.?\d*", text.replace(",", ""))
    return float(nums[-1]) if nums else None

# === Step 2: Self-consistency ===

def self_consistency(question, n=8, temperature=0.7):
    answers = []
    for _ in range(n):
        text = run_one(cot_prompt(question), temperature=temperature)
        ans = extract_answer(text)
        if ans is not None:
            answers.append(ans)
    if not answers:
        return None
    counts = Counter(answers)
    return counts.most_common(1)[0][0]

# === Step 3: Train a tiny outcome reward model ===

class ORM(nn.Module):
    def __init__(self, base_model):
        super().__init__()
        self.base = base_model
        self.head = nn.Linear(base_model.hidden_size, 1)

    def forward(self, input_ids, attention_mask):
        h = self.base(input_ids, attention_mask=attention_mask).last_hidden_state
        last = h[torch.arange(h.size(0)), attention_mask.sum(dim=1) - 1]
        return self.head(last).squeeze(-1)

# === Step 4: Best-of-N with the ORM ===

def bon(question, n=8, temperature=0.7):
    candidates = []
    for _ in range(n):
        text = run_one(cot_prompt(question), temperature=temperature)
        score = orm.score(question, text)
        candidates.append((score, text))
    candidates.sort(key=lambda x: -x[0])
    best = candidates[0][1]
    return extract_answer(best)

# === Step 5: Train a tiny PRM ===

def rollout_label(question, prefix, m=8):
    correct = 0
    for _ in range(m):
        continuation = run_one(prefix, temperature=0.7)
        ans = extract_answer(prefix + continuation)
        if ans == ground_truth[question]:
            correct += 1
    return correct / m

# === Step 6: Step-level Best-of-N with the PRM ===

def step_level_bon(question, k=4, max_steps=12):
    chain = ""
    for _ in range(max_steps):
        candidates = []
        for _ in range(k):
            step = sample_step(question, chain, temperature=0.7)
            score = prm.score(question, chain + step)
            candidates.append((score, step))
        candidates.sort(key=lambda x: -x[0])
        best_step = candidates[0][1]
        chain += best_step
        if has_final_answer(chain):
            break
    return extract_answer(chain)

# === Step 7: A tiny MCTS over reasoning steps ===

def mcts(question, n_iter=32, k_expand=4):
    root = Node(prompt=cot_prompt(question))
    for _ in range(n_iter):
        node = select(root)
        children = expand(node, k=k_expand)
        for child in children:
            rollout_value = rollout_and_grade(child)
            backup(child, rollout_value)
    return best_leaf_answer(root)
