"""
Project 3: Building A Tokenizer

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 1: Start from bytes, not characters ===

text = "hello 👋"
data = text.encode("utf-8")
print(list(data))
# [104, 101, 108, 108, 111, 32, 240, 159, 145, 139]

# === Step 2: Count adjacent pairs ===

[104, 101, 108, 108, 111]

from collections import Counter

def get_stats(ids: list) -> Counter:
    counts = Counter()
    for a, b in zip(ids, ids[1:]):
        counts[(a, b)] += 1
    return counts

# === Step 3: Merge the most frequent pair ===

def merge(ids: list, pair: tuple, new_id: int) -> list:
    out = []
    i = 0
    while i < len(ids):
        if i < len(ids) - 1 and ids[i] == pair[0] and ids[i + 1] == pair[1]:
            out.append(new_id)
            i += 2
        else:
            out.append(ids[i])
            i += 1
    return out

# === Step 4: Train the tokenizer to a target vocabulary size ===

ids = list(text.encode("utf-8"))
merges = {}
vocab = {i: bytes([i]) for i in range(256)}

for new_id in range(256, V):
    stats = get_stats(ids)
    pair = max(stats, key=stats.get)
    ids = merge(ids, pair, new_id)
    merges[pair] = new_id
    vocab[new_id] = vocab[pair[0]] + vocab[pair[1]]

# === Step 5: Build encode and decode ===

def decode(ids: list, vocab: dict) -> str:
    raw = b"".join(vocab[i] for i in ids)
    return raw.decode("utf-8", errors="replace")

def encode(text: str, merges: dict) -> list:
    ids = list(text.encode("utf-8"))
    while len(ids) >= 2:
        stats = {(a, b): i for i, (a, b) in enumerate(zip(ids, ids[1:]))}
        pair = min(stats, key=lambda p: merges.get(p, float("inf")))
        if pair not in merges:
            break
        ids = merge(ids, pair, merges[pair])
    return ids

# === Step 8: Plot tokens-per-sentence vs vocabulary size ===

sizes = [256, 1024, 4096, 8192]
results = []

for vocab_size in sizes:
    tokenizer = train_bpe(corpus_text, vocab_size)
    token_counts = []
    for sentence in sample_sentences:
        ids = tokenizer.encode(sentence)
        token_counts.append(len(ids))
    avg_tokens = sum(token_counts) / len(token_counts)
    results.append((vocab_size, avg_tokens))

# === Step 9: Build a token visualizer ===

tokens = tokenizer.encode("replaying the song")
for tid in tokens:
    piece = tokenizer.vocab[tid].decode("utf-8", errors="replace")
    print(f"[{piece}]")

# === Step 10: Compare to a production tokenizer ===

import tiktoken

enc = tiktoken.get_encoding("gpt2")
print(enc.encode("replaying the song"))
