"""
Project 27: Quantization and Deployment

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 2: Implement basic INT8 post-training quantization ===

import torch

def quantize_int8_symmetric(w: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    max_abs = w.abs().max()
    scale = max_abs / 127.0 if max_abs > 0 else torch.tensor(1.0, device=w.device)
    q = torch.clamp(torch.round(w / scale), -127, 127).to(torch.int8)
    return q, scale

def dequantize_int8(q: torch.Tensor, scale: torch.Tensor) -> torch.Tensor:
    return q.float() * scale

# === Step 3: Quantize one layer first, not the whole model ===

import torch

def layer_error(linear: torch.nn.Linear, x: torch.Tensor) -> tuple[float, float]:
    with torch.no_grad():
        y_fp = linear(x)

        q_w, scale = quantize_int8_symmetric(linear.weight.data)
        w_hat = dequantize_int8(q_w, scale)

        y_q = x @ w_hat.t()
        if linear.bias is not None:
            y_q = y_q + linear.bias

        mse = torch.mean((y_fp - y_q) ** 2).item()
        max_err = torch.max((y_fp - y_q).abs()).item()
        return mse, max_err

# === Step 4: Move from one layer to the full model ===

import torch

def quantize_model_int8(model: torch.nn.Module) -> dict:
    qstate = {}
    for name, module in model.named_modules():
        if isinstance(module, torch.nn.Linear):
            q_w, scale = quantize_int8_symmetric(module.weight.data)
            qstate[name] = {
                "q_weight": q_w.cpu(),
                "scale": scale.cpu(),
                "bias": None if module.bias is None else module.bias.data.cpu()
            }
    return qstate

# === Step 6: Implement INT4 quantization ===

import torch

def quantize_int4_groupwise(
    w: torch.Tensor, group_size: int = 64
) -> tuple[torch.Tensor, torch.Tensor]:
    flat = w.flatten()
    n = flat.numel()

    q_groups = []
    scales = []

    for i in range(0, n, group_size):
        chunk = flat[i:i+group_size]
        max_abs = chunk.abs().max()
        scale = max_abs / 7.0 if max_abs > 0 else torch.tensor(1.0, device=w.device)
        q = torch.clamp(torch.round(chunk / scale), -8, 7).to(torch.int8)
        q_groups.append(q)
        scales.append(scale)

    q = torch.cat(q_groups).view_as(w)
    scales = torch.stack(scales)
    return q, scales
