"""
Project 4: Attention From Scratch

Canonical runnable build for this project. Generated by tools/extract_code.py
from the book's chapter markdown — re-run that tool to regenerate.
"""

# === Step 2: Produce queries, keys, and values ===

Q = x @ W_Q
K = x @ W_K
V = x @ W_V

# === Step 3: Compute raw attention scores ===

scores = Q @ K.T

# === Step 4: Scale the scores ===

scores = (Q @ K.T) / math.sqrt(d_head)

# === Step 5: Turn scores into attention weights with softmax ===

weights = torch.softmax(scores, dim=-1)

# === Step 6: Mix the values ===

out = weights @ V

# === Step 8: Add causal masking ===

mask = torch.tril(torch.ones(T, T))
scores = scores.masked_fill(mask == 0, float('-inf'))

# === Step 11: Minimal multi-head implementation ===

# x: (T, d_model)
Q = x @ W_Q
K = x @ W_K
V = x @ W_V

# reshape to (H, T, d_head)
Q = Q.view(T, H, d_head).transpose(0, 1)
K = K.view(T, H, d_head).transpose(0, 1)
V = V.view(T, H, d_head).transpose(0, 1)

scores = (Q @ K.transpose(-2, -1)) / math.sqrt(d_head)   # (H, T, T)
scores = scores.masked_fill(mask == 0, float('-inf'))
weights = torch.softmax(scores, dim=-1)
head_out = weights @ V                                   # (H, T, d_head)

# back to (T, d_model)
out = head_out.transpose(0, 1).contiguous().view(T, d_model)

# === Step 12: Add the output projection ===

final = out @ W_O

# === Step 14: Measure per-head attention entropy ===

entropy = -(weights * (weights.clamp_min(1e-9).log())).sum(dim=-1)  # (H, T)
mean_entropy_per_head = entropy.mean(dim=-1)                        # (H,)
